name: scholarx
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Hanuman
      fonts: 
        - asset: assets/fonts/HanumanRegular.ttf
          weight: 400
        - asset: assets/fonts/HanumanBold.ttf
          weight: 700
